import { spawn, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { WorkerSpawner, SpawnResult, SpawnInfo } from './worker-spawner.js';
import { WorkerSpawnRequest } from '../session/types.js';

/**
 * Windows Terminal worker spawner.
 * Spawns Claude Code workers in new Windows Terminal tabs.
 */
export class WindowsTerminalSpawner implements WorkerSpawner {
  private wtPath: string | null = null;

  getName(): string {
    return 'Windows Terminal';
  }

  /**
   * Checks if Windows Terminal is available.
   * Uses fs.existsSync and 'where' command to avoid opening windows.
   */
  isAvailable(): boolean {
    if (this.wtPath !== null) {
      return true;
    }

    // Check if wt.exe exists in WindowsApps
    const windowsAppsPath = path.join(
      process.env.LOCALAPPDATA || '',
      'Microsoft',
      'WindowsApps',
      'wt.exe'
    );

    if (fs.existsSync(windowsAppsPath)) {
      this.wtPath = windowsAppsPath;
      return true;
    }

    // Check if wt.exe is in PATH using 'where' command (doesn't open windows)
    try {
      const result = spawnSync('where', ['wt.exe'], {
        stdio: 'pipe',
        windowsHide: true,
      });
      if (result.status === 0) {
        this.wtPath = 'wt.exe';
        return true;
      }
    } catch {
      // Ignore errors
    }

    return false;
  }

  /**
   * Spawns a Claude Code worker in a new Windows Terminal tab.
   */
  async spawn(request: WorkerSpawnRequest): Promise<SpawnResult> {
    const spawnId = crypto.randomUUID();
    const spawnedAt = new Date().toISOString();

    if (!this.isAvailable()) {
      return {
        success: false,
        spawnId,
        spawnedAt,
        error: 'Windows Terminal is not available',
      };
    }

    // Write spawn info to worktree for tracking
    const spawnInfo: SpawnInfo = {
      spawnId,
      spawnedAt,
      issueNumber: request.issueNumber,
    };
    await this.writeSpawnInfo(request.workingDirectory, spawnInfo);

    const tabTitle = `Issue #${request.issueNumber}`;

    // Build the Claude command - simple, no wrapper
    const claudeCommand = this.buildClaudeCommand(request);

    // Windows Terminal command to open a new tab
    // Use cmd /k to keep terminal open after Claude exits (for debugging)
    const args = [
      'new-tab',
      '--title', tabTitle,
      '--startingDirectory', request.workingDirectory,
      'cmd', '/k', claudeCommand,
    ];

    return new Promise((resolve) => {
      const proc = spawn(this.wtPath || 'wt.exe', args, {
        detached: true,
        stdio: 'ignore',
      });

      proc.on('error', (error) => {
        resolve({
          success: false,
          spawnId,
          spawnedAt,
          error: `Failed to spawn Windows Terminal: ${error.message}`,
        });
      });

      // Don't wait for the process - it's detached
      proc.unref();

      // Give it a moment to start
      setTimeout(() => {
        resolve({
          success: true,
          spawnId,
          spawnedAt,
        });
      }, 500);
    });
  }

  /**
   * Writes spawn info to the worktree for tracking.
   */
  private async writeSpawnInfo(workingDirectory: string, info: SpawnInfo): Promise<void> {
    const claudeDir = path.join(workingDirectory, '.claude');
    if (!fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }
    const infoPath = path.join(claudeDir, 'spawn-info.json');
    await fs.promises.writeFile(infoPath, JSON.stringify(info, null, 2), 'utf-8');
  }

  /**
   * Builds the Claude command to run in the terminal.
   */
  private buildClaudeCommand(request: WorkerSpawnRequest): string {
    // Bootstrap instruction tells Claude where to find full instructions
    // The full prompt is already written to .claude/session-prompt.md by writeWorkerPrompt()
    const bootstrap =
      `You are an autonomous worker for Issue #${request.issueNumber}. ` +
      `Read .claude/session-prompt.md for your full instructions and begin.`;

    // Escape quotes for Windows cmd by doubling them
    const escaped = bootstrap.replace(/"/g, '""');

    // --dangerously-skip-permissions bypasses trust prompts for new worktree directories
    // This is safe because: issues come from user's own GitHub repo, worktrees are from
    // trusted branches, and prompts are generated by our code
    return `claude --dangerously-skip-permissions "${escaped}"`;
  }
}

/**
 * Creates the appropriate spawner for the current platform.
 */
export function createSpawner(): WorkerSpawner {
  if (process.platform === 'win32') {
    return new WindowsTerminalSpawner();
  }

  // TODO: Add support for other platforms (macOS with iTerm, Linux with tmux)
  throw new Error(`No worker spawner available for platform: ${process.platform}`);
}
