import { spawn, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { WorkerSpawner, SpawnResult, SpawnInfo } from './worker-spawner.js';
import { WorkerSpawnRequest } from '../session/types.js';

/**
 * Windows Terminal worker spawner.
 * Spawns Claude Code workers in new Windows Terminal tabs.
 */
export class WindowsTerminalSpawner implements WorkerSpawner {
  private wtPath: string | null = null;

  getName(): string {
    return 'Windows Terminal';
  }

  /**
   * Checks if Windows Terminal is available.
   * Uses fs.existsSync and 'where' command to avoid opening windows.
   */
  isAvailable(): boolean {
    if (this.wtPath !== null) {
      return true;
    }

    // Check if wt.exe exists in WindowsApps
    const windowsAppsPath = path.join(
      process.env.LOCALAPPDATA || '',
      'Microsoft',
      'WindowsApps',
      'wt.exe'
    );

    if (fs.existsSync(windowsAppsPath)) {
      this.wtPath = windowsAppsPath;
      return true;
    }

    // Check if wt.exe is in PATH using 'where' command (doesn't open windows)
    try {
      const result = spawnSync('where', ['wt.exe'], {
        stdio: 'pipe',
        windowsHide: true,
      });
      if (result.status === 0) {
        this.wtPath = 'wt.exe';
        return true;
      }
    } catch {
      // Ignore errors
    }

    return false;
  }

  /**
   * Spawns a Claude Code worker in a new Windows Terminal tab.
   */
  async spawn(request: WorkerSpawnRequest): Promise<SpawnResult> {
    const spawnId = crypto.randomUUID();
    const spawnedAt = new Date().toISOString();

    if (!this.isAvailable()) {
      return {
        success: false,
        spawnId,
        spawnedAt,
        error: 'Windows Terminal is not available',
      };
    }

    // Write spawn info to worktree for tracking
    const spawnInfo: SpawnInfo = {
      spawnId,
      spawnedAt,
      issueNumber: request.issueNumber,
    };
    await this.writeSpawnInfo(request.workingDirectory, spawnInfo);

    const tabTitle = `Issue #${request.issueNumber}`;

    // Build the Claude command
    const claudeCommand = this.buildClaudeCommand(request);

    // Write wrapper scripts (.cmd and .ps1) and get path to the batch wrapper
    const wrapperScriptPath = await this.writeWrapperScripts(request.workingDirectory, claudeCommand);
    // Run the batch file directly - no PowerShell wrapper needed
    const wrapperCommand = `"${wrapperScriptPath}"`;

    // Windows Terminal command to open a new tab
    // Use cmd /c with wrapper - wrapper decides whether to close or stay open
    const args = [
      'new-tab',
      '--title', tabTitle,
      '--startingDirectory', request.workingDirectory,
      'cmd', '/c', wrapperCommand,
    ];

    return new Promise((resolve) => {
      const proc = spawn(this.wtPath || 'wt.exe', args, {
        detached: true,
        stdio: 'ignore',
      });

      proc.on('error', (error) => {
        resolve({
          success: false,
          spawnId,
          spawnedAt,
          error: `Failed to spawn Windows Terminal: ${error.message}`,
        });
      });

      // Don't wait for the process - it's detached
      proc.unref();

      // Give it a moment to start
      setTimeout(() => {
        resolve({
          success: true,
          spawnId,
          spawnedAt,
        });
      }, 500);
    });
  }

  /**
   * Writes spawn info to the worktree for tracking.
   */
  private async writeSpawnInfo(workingDirectory: string, info: SpawnInfo): Promise<void> {
    const claudeDir = path.join(workingDirectory, '.claude');
    if (!fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }
    const infoPath = path.join(claudeDir, 'spawn-info.json');
    await fs.promises.writeFile(infoPath, JSON.stringify(info, null, 2), 'utf-8');
  }

  /**
   * Writes wrapper scripts that manage Claude's lifecycle.
   *
   * Uses a two-script architecture:
   * 1. worker-wrapper.cmd - Batch file that runs Claude directly and controls exit code
   * 2. session-watcher.ps1 - Hidden PowerShell script that monitors session status
   *
   * This approach solves the exit code problem: when taskkill terminates processes,
   * the batch file still runs and can exit with code 0 for clean terminal closure.
   */
  private async writeWrapperScripts(worktreePath: string, claudeCommand: string): Promise<string> {
    const claudeDir = path.join(worktreePath, '.claude');
    if (!fs.existsSync(claudeDir)) {
      fs.mkdirSync(claudeDir, { recursive: true });
    }

    // Write the session watcher PowerShell script
    const watcherPath = path.join(claudeDir, 'session-watcher.ps1');
    const watcherScript = `# Session Watcher Script - Auto-generated by orchestrator
# Monitors session status and signals wrapper when to exit cleanly

param([string]$sessionPath)

$ErrorActionPreference = 'SilentlyContinue'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

while ($true) {
    Start-Sleep -Seconds 2

    try {
        $session = Get-Content $sessionPath -Raw -ErrorAction Stop | ConvertFrom-Json
        $status = $session.status

        if ($status -eq 'complete' -or $status -eq 'cancelled') {
            # Create signal file for wrapper to detect
            "clean" | Out-File (Join-Path $scriptDir 'exit-signal') -Force

            # Kill Claude and related processes
            # Find cmd.exe processes with claude in command line and kill their trees
            Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
                $_.Name -eq 'cmd.exe' -and $_.CommandLine -like '*claude*--dangerously-skip-permissions*'
            } | ForEach-Object {
                Start-Process -FilePath 'taskkill' -ArgumentList '/T', '/F', '/PID', $_.ProcessId -NoNewWindow -Wait
            }

            exit 0
        }
    } catch {
        # Ignore errors, keep polling
    }
}
`;
    await fs.promises.writeFile(watcherPath, watcherScript, 'utf-8');

    // Write the batch wrapper script
    const wrapperPath = path.join(claudeDir, 'worker-wrapper.cmd');

    // Escape the claude command for batch - double up percent signs
    const batchClaudeCommand = claudeCommand.replace(/%/g, '%%');

    const wrapperScript = `@echo off
REM Worker Wrapper Script - Auto-generated by orchestrator
REM Manages Claude lifecycle and controls exit code for clean terminal closure

setlocal EnableDelayedExpansion

REM Read session path from context
for /f "usebackq tokens=*" %%a in (\`powershell -NoProfile -Command "(Get-Content 'session-context.json' | ConvertFrom-Json).sessionFilePath"\`) do set "SESSION_PATH=%%a"

if "%SESSION_PATH%"=="" (
    echo ERROR: No sessionFilePath in session-context.json
    pause
    exit /b 1
)

echo Worker started. Monitoring session: %SESSION_PATH%
echo.

REM Start background watcher (hidden PowerShell window)
start "" /b powershell -WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -File ".claude\\session-watcher.ps1" "%SESSION_PATH%"

REM Run Claude directly (blocking, output visible, interactive)
cmd /c ${batchClaudeCommand}

REM Claude exited - check for clean exit signal
if exist ".claude\\exit-signal" (
    del ".claude\\exit-signal" >nul 2>&1
    exit /b 0
)

REM Not clean exit - show status and wait for user input
echo.
echo ==================================================

REM Get current status
for /f "usebackq tokens=*" %%s in (\`powershell -NoProfile -Command "(Get-Content '%SESSION_PATH%' | ConvertFrom-Json).status"\`) do set "STATUS=%%s"
echo   Worker stopped. Status: %STATUS%

REM Get stuck reason if any
for /f "usebackq tokens=*" %%r in (\`powershell -NoProfile -Command "$s=(Get-Content '%SESSION_PATH%' | ConvertFrom-Json).stuckReason; if($s){$s}"\`) do (
    if not "%%r"=="" echo   Reason: %%r
)

echo   Review the output above, then press any key...
echo ==================================================
pause >nul
`;
    await fs.promises.writeFile(wrapperPath, wrapperScript, 'utf-8');

    return wrapperPath;
  }

  /**
   * Builds the Claude command to run in the terminal.
   */
  private buildClaudeCommand(request: WorkerSpawnRequest): string {
    // Bootstrap instruction tells Claude where to find full instructions
    // The full prompt is already written to .claude/session-prompt.md by writeWorkerPrompt()
    const bootstrap =
      `You are an autonomous worker for Issue #${request.issueNumber}. ` +
      `Read .claude/session-prompt.md for your full instructions and begin.`;

    // Escape quotes for Windows cmd by doubling them
    const escaped = bootstrap.replace(/"/g, '""');

    // --dangerously-skip-permissions bypasses trust prompts for new worktree directories
    // This is safe because: issues come from user's own GitHub repo, worktrees are from
    // trusted branches, and prompts are generated by our code
    return `claude --dangerously-skip-permissions "${escaped}"`;
  }
}

/**
 * Creates the appropriate spawner for the current platform.
 */
export function createSpawner(): WorkerSpawner {
  if (process.platform === 'win32') {
    return new WindowsTerminalSpawner();
  }

  // TODO: Add support for other platforms (macOS with iTerm, Linux with tmux)
  throw new Error(`No worker spawner available for platform: ${process.platform}`);
}
